config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"
  
  resources :products do
    collection do
      post :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  searchkick

  SORT_BY = [["Relevance", "relevance"], ["Newest", "newest"], ["Oldest", "oldest"], ["Lowest price", "lprice"], ["Highest price", "hprice"]]
  PRICE_OPTIONS = [["Less Than", "lt"], ["Equal To", "eq"], ["Greater Than", "gt"]]

  validates :title, :description, :country, :tags, :price, presence: true

  def self.search_kick params
    search_term = params[:q].present? ? params[:q] : "*"

    price_condition, country_condition = {}, {}
    if params[:price].present?
      if params[:price_option].to_s == "lt"
        price_condition = {price: {lt: params[:price]}}
      elsif params[:price_option].to_s == "gt"
        price_condition = {price: {gt: params[:price]}}
      else
        price_condition = {price: params[:price]}
      end
    end
    country_condition = {country: params[:country]} if params[:country].present?
    conditions = {_and: [country_condition, price_condition]}
    sort_by_order = Product.get_sort_by_order(params[:sort_by])
    
    Product.search search_term, fields: ["title^10", "description", "price", "tags", "country"], where: conditions, order: sort_by_order, page: params[:page], per_page: 15
  end

  def self.get_sort_by_order sort_by
    if sort_by == "newest"
      sort_by_order = {created_at: :desc}
    elsif sort_by == "oldest"
      sort_by_order = {created_at: :asc}
    elsif sort_by == "hprice"
      sort_by_order = {price: :desc}
    elsif sort_by == "lprice"
      sort_by_order = {price: :asc}
    else
      sort_by_order = {_score: :desc}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.search_kick(params)
  end

  def search
    redirect_to products_path(q: params[:q], sort_by: params[:sort_by], country: params[:country], price: params[:price], price_option: params[:price_option])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductSearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container mt-4 mb-4">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="margin:24px 0;">
    <%= link_to "All Products", root_path, class: "navbar-brand" %>
    <ul class="navbar-nav mr-auto"></ul>
    <%= form_with url: search_products_path, method: :post, class: "form-inline my-2 my-lg-0 sort-by-form mr-4" do |f| %>
      <%= f.text_field :country, value: params[:country], class: "hidden" %>
      <%= f.text_field :price, value: params[:price], class: "hidden" %>
      <%= f.text_field :price_option, value: params[:price_option], class: "hidden" %>
      <%= f.text_field :q, value: params[:q], class: "hidden" %>
      <%= f.select :sort_by, options_for_select(params[:q].present? ? Product::SORT_BY : Product::SORT_BY[1..-1], selected: Product::SORT_BY.select{|o| o[1] == params[:sort_by]}.flatten), prompt: "Sort By", class: 'form-control mr-sm-2 sort-by-dropdown' %>
      <%= f.submit 'Search', class: 'btn btn-success my-2 my-sm-0 mr-sm-2 hidden' %>
    <% end %>
    <%= form_with url: search_products_path, method: :post, class: "form-inline my-2 my-lg-0" do |f| %>
      <%= f.text_field :q, placeholder: 'Search', value:  params[:q], required: true, class: 'form-control mr-sm-2' %>
      <%= f.submit 'Search', class: 'btn btn-success my-2 my-sm-0 mr-sm-2' %>
    <% end %>
    <%= link_to "Clear Search", root_path, class: "btn btn-light" if params[:q].present? %>
  </nav>

  <nav class="navbar navbar-expand-lg" style="margin:24px 0;">
    <h4 class="m-0 mr-2">Filters: </h4>
    <%= form_with url: search_products_path, method: :post, class: "form-inline my-2 my-lg-0" do |f| %>
      <%= f.text_field :sort_by, value: params[:sort_by], class: "hidden" %>
      <%= f.text_field :q, value: params[:q], class: "hidden" %>
      <%= f.select :country, options_for_select(Product.all.map(&:country).uniq, selected: params[:country]), prompt: "Select Country", class: 'form-control mr-sm-2' %>
      <%= f.text_field :price, placeholder: "Enter price", value: params[:price], class: "ml-4 mr-2" %>
      <%= f.select :price_option, options_for_select(Product::PRICE_OPTIONS, selected: Product::PRICE_OPTIONS.select{|o| o[1] == params[:price_option]}.flatten), prompt: "Select Price Option", class: 'form-control' %>
      <%= f.submit 'Apply Filters', class: 'btn btn-success my-2 my-sm-0 ml-4' %>
    <% end %>
    <%= link_to "Clear Filter", root_path, class: "btn btn-secondary ml-2" if params[:price].present? || params[:country].present? %>
  </nav>

  <div class="row mb-2">
    <% @products.each do |product| %>
      <div class="col-lg-4 col-md-6 col-12 mt-4" >
        <div class="card card-body" data-price="<%= product.price %>" data-country="<%= product.country %>" data-tags="<%= product.tags %>" data-created-at="<%= product.created_at.strftime('%d %b, %Y %H:%M') %>" data-title="<%= product.title %>" data-description="<%= product.description %>">
          <h4 class="card-title"><%= product.title.truncate(30) %></h4>
          <p class="card-text"><span class="card-description"><%= product.description.truncate(82) %></span><br><small>Price: <%= product.price %></small></p>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @products %>
</div>

<div class="modal fade" id="product_details" tabindex="-1" role="dialog" aria-labelledby="productDetailsModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="productDetailsModalLabel"><strong></strong></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="description"><b>Description:</b> <span></span></p>
        <p class="country"><b>Country:</b> <span></span></p>
        <p class="price"><b>Price:</b> <span></span></p>
        <p class="tags"><b>Tags:</b> <span></span></p>
        <p class="created_at"><b>Created At:</b> <span></span></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>